#!/usr/bin/env bash
# claim.sh — CLAIMS REGISTRY (anti-duplicate, parallel-safe). RULES R8.
# The same agent can run in parallel (overlapping schedules, several machines). Without a
# claim taken BEFORE starting, two instances do the same task.
#
#   claim.sh take "<scope>" "<agent>" ["notes"]   → takes a task. REFUSES (exit 3) if an OPEN
#        claim has the same scope. Prints the open claims so you can spot a fuzzy duplicate.
#        Last stdout line = the claim ID (contract for callers).
#   claim.sh set <id> <STATUS> ["notes"]          → IN-PROGRESS · REVIEW · SHIPPED · DONE · RELEASED
#   claim.sh list                                 → open claims
#   claim.sh mine "<agent>"                       → your open claims
#   claim.sh render                               → regenerate bus/claims.md
# Store: state/claims.jsonl (append-only, union-merged). View: bus/claims.md (generated).
# Sync: best-effort through scripts/sync.sh (never fatal — a take that fails to print its ID
# makes the agent re-take → duplicate). COMPANY_OS_NOSYNC=1 disables sync (tests).
set -euo pipefail
. "$(dirname "$0")/lib.sh"
STORE="state/claims.jsonl"; VIEW="bus/claims.md"; LOCKD="state/.claims.lock.d"
mkdir -p state bus; touch "$STORE"
RUN_ID="${COMPANY_OS_RUN_ID:-$$-$(epoch)}"
CMD="${1:-}"; shift || true

render(){ python3 - "$STORE" "$VIEW" <<'PY'
import json, sys
store, view = sys.argv[1], sys.argv[2]
cur = {}
for ln in open(store, encoding="utf-8", errors="replace"):
    ln = ln.strip()
    if not ln: continue
    try: e = json.loads(ln); cur[e["id"]] = e
    except Exception: pass
OPEN = sorted([e for e in cur.values() if e.get("status") not in ("DONE","RELEASED")], key=lambda e: e.get("ts",""), reverse=True)
CLOSED = sorted([e for e in cur.values() if e.get("status") in ("DONE","RELEASED")], key=lambda e: e.get("ts",""), reverse=True)
DOT = {"CLAIMED":"🟡","IN-PROGRESS":"🔵","REVIEW":"🟣","SHIPPED":"🟢","DONE":"✅","RELEASED":"⚪"}
out = ["# bus/claims.md — claims registry (generated by scripts/claim.sh — DO NOT EDIT BY HAND)", "",
       "> Before starting a task: `scripts/claim.sh take \"<scope>\" \"<agent>\"`.",
       "> Update: `scripts/claim.sh set <id> <IN-PROGRESS|REVIEW|SHIPPED|DONE|RELEASED>`.",
       "> A scope already OPEN = do not take it (duplicate). RULES R8.", "", "## Open", "",
       "| ID | Scope | Agent · run | Status | Updated | Notes |", "|---|---|---|---|---|---|"]
for e in OPEN:
    out.append(f"| `{e['id']}` | {e.get('scope','')} | {e.get('agent','')} · {str(e.get('run',''))[:14]} | {DOT.get(e.get('status',''),'')} {e.get('status','')} | {e.get('ts','')[:19]} | {e.get('notes','')} |")
if not OPEN: out.append("| — | _no open claim_ | | | | |")
out += ["", "## Closed (last 20)", "", "| ID | Scope | Agent | Status | Updated |", "|---|---|---|---|---|"]
for e in CLOSED[:20]:
    out.append(f"| `{e['id']}` | {e.get('scope','')} | {e.get('agent','')} | {DOT.get(e.get('status',''),'')} {e.get('status','')} | {e.get('ts','')[:19]} |")
open(view, "w", encoding="utf-8").write("\n".join(out) + "\n")
PY
}
last_field(){ # $1=id $2=field → last non-empty value for that id
  python3 - "$STORE" "$1" "$2" <<'PY'
import json, sys
store, cid, field = sys.argv[1:4]; last = ""
for ln in open(store, encoding="utf-8", errors="replace"):
    ln = ln.strip()
    if not ln: continue
    try: e = json.loads(ln)
    except Exception: continue
    if e.get("id") == cid and str(e.get(field, "")).strip(): last = e[field]
print(last)
PY
}
append(){ # id scope agent status notes
  printf '{"id":"%s","scope":%s,"agent":%s,"run":"%s","status":"%s","notes":%s,"ts":"%s"}\n' \
    "$1" "$(json_str "$2")" "$(json_str "$3")" "$RUN_ID" "$4" "$(json_str "$5")" "$(now_iso)" >> "$STORE"
}
git_sync(){ [ "${COMPANY_OS_NOSYNC:-}" = "1" ] && return 0
  bash scripts/sync.sh "claims: $1" >/dev/null 2>&1 || say "⚠️  claim written LOCALLY but not pushed — other machines will see it at the next sync"
  return 0; }

case "$CMD" in
  take)
    SCOPE="${1:?usage: take \"<scope>\" \"<agent>\" [notes]}"; AGENT="${2:?agent required}"; NOTES="${3:-}"
    lock_take "$LOCKD"; trap 'lock_drop "$LOCKD"' EXIT
    DUP=$(python3 - "$STORE" "$SCOPE" <<'PY'
import json, sys
store, scope = sys.argv[1], sys.argv[2].strip().lower(); cur = {}
for ln in open(store, encoding="utf-8", errors="replace"):
    ln = ln.strip()
    if not ln: continue
    try: e = json.loads(ln); cur[e["id"]] = e
    except Exception: pass
for e in cur.values():
    if e.get("status") not in ("DONE","RELEASED") and e.get("scope","").strip().lower() == scope:
        print(f"{e['id']}|{e.get('agent','')}|{e.get('status','')}"); break
PY
)
    if [ -n "$DUP" ]; then
      echo "⛔ ALREADY CLAIMED: this scope is open by → $DUP" >&2
      echo "   Do not take it (duplicate). Coordinate via bus/inbox/chief-of-staff/ or take another task." >&2
      render; sed -n '/## Open/,/## Closed/p' "$VIEW" >&2
      exit 3
    fi
    ID="c$(epoch)$(( RANDOM % 100 ))"
    append "$ID" "$SCOPE" "$AGENT" "CLAIMED" "$NOTES"
    render; lock_drop "$LOCKD"; trap - EXIT
    echo "✅ CLAIM $ID — $AGENT · $SCOPE"
    git_sync "take $ID ($AGENT)"
    echo "$ID" ;;
  set)
    ID="${1:?usage: set <id> <STATUS> [notes]}"; ST="${2:?status required}"; NOTES="${3:-}"
    case "$ST" in IN-PROGRESS|REVIEW|SHIPPED|DONE|RELEASED) ;; *) echo "invalid status: $ST (IN-PROGRESS|REVIEW|SHIPPED|DONE|RELEASED)" >&2; exit 1;; esac
    lock_take "$LOCKD"; trap 'lock_drop "$LOCKD"' EXIT
    grep -q "\"id\":\"$ID\"" "$STORE" || { echo "unknown id: $ID" >&2; exit 1; }
    AGENT="$(last_field "$ID" agent)"; SCOPE="$(last_field "$ID" scope)"   # keep the scope: current state = last event per id
    append "$ID" "$SCOPE" "$AGENT" "$ST" "$NOTES"
    render; lock_drop "$LOCKD"; trap - EXIT
    echo "→ $ID = $ST"
    git_sync "set $ID $ST" ;;
  list)   render; sed -n '/## Open/,/## Closed/p' "$VIEW" ;;
  mine)   AG="${1:?agent}"; render; grep -iE "\| $AG " "$VIEW" || echo "no open claim for $AG" ;;
  render) render; echo "view regenerated: $VIEW" ;;
  *) echo "usage: claim.sh take|set|list|mine|render — see header" >&2; exit 1 ;;
esac
