#!/usr/bin/env bash
# decision.sh — DECISIONS REGISTRY (real-time single source of truth, read by ALL). RULES R9.
# The founder decides in 1-1 with ONE agent → the others re-escalate unless it is recorded here
# the moment it happens.
#
#   decision.sh set "<short subject>" "<decision / state>" <STATUS> [who]
#        STATUS: DECIDED (founder decided) · PENDING (waits for the founder) ·
#                IN-PROGRESS (decided, executing) · DONE (executed/closed) · PARKED (deliberately later)
#        who: e.g. founder→growth, ops→founder
#   decision.sh list                  → regenerates and prints bus/DECISIONS.md
#   decision.sh show "<subject or fragment>"  → FULL detail (the view truncates to 250 chars)
#   decision.sh render                → regenerate the view only
# Store: state/decisions.jsonl (append-only, union-merged) · View: bus/DECISIONS.md · sync best-effort.
set -euo pipefail
. "$(dirname "$0")/lib.sh"
STORE="state/decisions.jsonl"; VIEW="bus/DECISIONS.md"; LOCKD="state/.decisions.lock.d"
mkdir -p state bus; touch "$STORE"
CMD="${1:-list}"; shift || true

render(){ python3 - "$STORE" "$VIEW" <<'PY'
import json, sys
store, view = sys.argv[1], sys.argv[2]; cur = {}
for ln in open(store, encoding="utf-8", errors="replace"):
    ln = ln.strip()
    if not ln: continue
    try: e = json.loads(ln); cur[e["subject"].strip().lower()] = e
    except Exception: pass
DOT = {"DECIDED":"✅","PENDING":"⏳","IN-PROGRESS":"🚧","DONE":"☑️","PARKED":"🧊"}
order = {"PENDING":0,"DECIDED":1,"IN-PROGRESS":2,"PARKED":3,"DONE":4}
MAX = 250
def clip(t):
    t = " ".join(str(t or "").split())
    return t if len(t) <= MAX else t[:MAX].rstrip() + " […]"
rows = sorted(cur.values(), key=lambda e: (order.get(e.get("status"), 9), e.get("ts", "")))
out = ["# bus/DECISIONS.md — decisions registry (generated by scripts/decision.sh — DO NOT EDIT BY HAND)", "",
       "> READ AT THE START OF EVERY RUN (RULES R9). The founder decides in 1-1: this file is the",
       "> ONLY source of truth on decisions. A ⏳ that became ✅ here = do NOT re-escalate.",
       "> Record any new decision: `scripts/decision.sh set …`", "",
       f"> ⚠️ Details are TRUNCATED to {MAX} characters — a « […] » means you do not have the full",
       "> context. Full text (mandatory before acting on a truncated row): `scripts/decision.sh show \"<subject>\"`.", "",
       "| Status | Subject | Decision / state | Who | Updated |", "|---|---|---|---|---|"]
for e in rows:
    out.append(f"| {DOT.get(e.get('status'),'')} {e.get('status','')} | **{e.get('subject','')}** | {clip(e.get('detail',''))} | {e.get('who','')} | {e.get('ts','')[:16]} |")
if not rows: out.append("| — | _no decision recorded yet_ | | | |")
open(view, "w", encoding="utf-8").write("\n".join(out) + "\n")
PY
}

case "$CMD" in
  set)
    SUBJECT="${1:?usage: set \"<subject>\" \"<detail>\" <STATUS> [who]}"; DETAIL="${2:?detail required}"; ST="${3:?status required}"; WHO="${4:-}"
    case "$ST" in DECIDED|PENDING|IN-PROGRESS|DONE|PARKED) ;; *) echo "invalid status: $ST (DECIDED|PENDING|IN-PROGRESS|DONE|PARKED)" >&2; exit 1;; esac
    lock_take "$LOCKD"; trap 'lock_drop "$LOCKD"' EXIT
    printf '{"subject":%s,"detail":%s,"status":"%s","who":%s,"ts":"%s"}\n' \
      "$(json_str "$SUBJECT")" "$(json_str "$DETAIL")" "$ST" "$(json_str "$WHO")" "$(now_iso)" >> "$STORE"
    render; lock_drop "$LOCKD"; trap - EXIT
    echo "✅ decision « $SUBJECT » → $ST"
    [ "${COMPANY_OS_NOSYNC:-}" = "1" ] || bash scripts/sync.sh "decisions: $SUBJECT → $ST" >/dev/null 2>&1 \
      || say "⚠️  decision written LOCALLY but not pushed — other machines will see it at the next sync" ;;
  list) render; cat "$VIEW" ;;
  render) render; echo "view regenerated: $VIEW" ;;
  show)
    Q="${1:?usage: show \"<subject or fragment>\"}"
    python3 - "$STORE" "$Q" <<'PY'
import json, sys
store, raw = sys.argv[1], sys.argv[2]; q = raw.strip().lower(); cur = {}
for ln in open(store, encoding="utf-8", errors="replace"):
    ln = ln.strip()
    if not ln: continue
    try: e = json.loads(ln); cur[e["subject"].strip().lower()] = e
    except Exception: pass
hits = [cur[q]] if q in cur else sorted((e for k, e in cur.items() if q in k), key=lambda e: e.get("subject",""))
if not hits:
    print(f"no decision matches « {raw} » — see bus/DECISIONS.md", file=sys.stderr); raise SystemExit(1)
for e in hits:
    print(f"## {e.get('subject','')}\nstatus: {e.get('status','')} · who: {e.get('who','')} · updated: {e.get('ts','')[:16]}\n\n{e.get('detail','')}\n")
PY
    ;;
  *) echo "usage: decision.sh set|list|show|render" >&2; exit 1 ;;
esac
